command: [
  "streamlit",
  "run",
  "app.py"
]

env:
  - name: DATABRICKS_HOST
    valueFrom: "databricks_host"
  - name: DATABRICKS_CLIENT_ID
    valueFrom: "databricks_client_id"
  - name: DATABRICKS_CLIENT_SECRET
    valueFrom: "databricks_client_secret"
  - name: COMBINED_ESTIMATIONS
    valueFrom: "combined_estimations"
  - name: NEW_SOURCE_REQUESTS
    valueFrom: "new_source_requests"
  - name: NEW_SOURCE_ESTIMATIONS
    valueFrom: "new_source_estimations"
  - name: SOURCE_SYSTEM_REQUESTS
    valueFrom: "source_system_requests"
  - name: SOURCE_SYSTEM_ESTIMATIONS
    valueFrom: "source_system_estimations"
  - name: ADMIN_USERS_TABLE
    valueFrom: "admin_users_table"