# Databricks notebook source
# EDH Cost Estimator - DISPATCHER
# Single entry point for the Ingestio app. Routes to either the
# existing-source or new-source estimator notebook based on
# `request_type`, and passes that form's fields through unchanged.
#
# WHY A DISPATCHER (not a native If/else condition task):
# Each form has its own, different parameter set. A dispatcher notebook
# that calls dbutils.notebook.run() lets the app send "whatever fields
# that form collected" as a single JSON blob, without needing to
# declare every possible field as a widget on this notebook too. Adding
# a field to one form later does NOT require touching this dispatcher -
# only the target notebook's own widget declarations need to match.
#
# WHY request_id IS GENERATED BY THE APP, NOT HERE:
# Both target notebooks already accept request_id as an input widget and
# write it into their Delta tables. The app generates this value before
# calling run-now and passes it through in the payload, so the resulting
# Delta row can be identified/traced back to the original form submission
# later (e.g. for support/debugging), even though the app itself does not
# poll for or display the result directly - see note below.
#
# WHY THIS DISPATCHER DOESN'T CAPTURE OR RETURN A RESULT:
# The app does not consume job output at all. It fires the request and
# moves on; results are surfaced later via a separate dashboard section
# that reads the Delta tables directly (edh_cost_estimations /
# edh_newsource_estimations), independent of this job run. This keeps
# the app's integration surface to a single call (run-now) with nothing
# to poll or parse afterward.

# COMMAND ----------

import json

dbutils.widgets.text("request_type", "")   # "existing_source" or "new_source"
dbutils.widgets.text("payload", "{}")      # JSON string: that form's fields, including request_id

request_type = dbutils.widgets.get("request_type")
payload_raw  = dbutils.widgets.get("payload")

try:
    payload = json.loads(payload_raw)
except json.JSONDecodeError as e:
    raise ValueError(f"payload widget is not valid JSON: {e}\nReceived: {payload_raw}")

if "request_id" not in payload or not payload["request_id"]:
    raise ValueError(
        "payload must include a non-empty 'request_id', generated by the "
        "app BEFORE calling run-now, so the app knows what to poll for."
    )

# Databricks notebook widget params must be strings - the target notebooks
# already do their own type casting (float(), int(), .lower()=='true', etc.)
# on whatever they receive, same as they do today when called directly.
str_payload = {k: str(v) for k, v in payload.items()}

# COMMAND ----------

NOTEBOOK_PATHS = {
    "existing_source": "EDH_Cost_Estimator_Job",
    "new_source":       "EDH_New_Source_Estimator_Job",
}

if request_type not in NOTEBOOK_PATHS:
    raise ValueError(
        f"Unknown request_type '{request_type}'. "
        f"Must be one of: {list(NOTEBOOK_PATHS.keys())}"
    )

target_notebook = NOTEBOOK_PATHS[request_type]

print(f"Dispatching request_id={payload['request_id']}  request_type={request_type}  -> {target_notebook}")

# COMMAND ----------

# Adjust the path below to match where these notebooks actually live in
# your workspace (e.g. "/Workspace/EnterpriseDataHub/EDH/notebooks/JOBS/...").
# 600 second timeout is a starting point - tune to whatever this estimator
# actually takes to run plus headroom.
#
# No need to capture or relay a return value here: the app does not
# consume job output at all. Its dashboard section reads the relevant
# Delta table (edh_cost_estimations or edh_newsource_estimations)
# independently, whenever the user views it - completely decoupled from
# this job run. This job's only responsibility is: route correctly, run
# the right notebook, let it write its row to Delta. Databricks Jobs UI
# already shows run success/failure automatically (any unhandled
# exception in the target notebook marks the run as failed) - no
# explicit dbutils.notebook.exit() needed just for that.

dbutils.notebook.run(
    target_notebook,
    600,
    str_payload,
)
